// <auto-generated />
namespace PEDRO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alteradocampotipodoarquivoparaextensao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteradocampotipodoarquivoparaextensao));
        
        string IMigrationMetadata.Id
        {
            get { return "201706221206152_alterado campo tipo do arquivo para extensao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
