// <auto-generated />
namespace PEDRO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class trocadevariavelchaveestrangeira : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trocadevariavelchaveestrangeira));
        
        string IMigrationMetadata.Id
        {
            get { return "201705111116439_troca de variavel chave estrangeira"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
